# Generated by Django 4.0.5 on 2022-07-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('number', models.BigIntegerField(max_length=10)),
                ('account_ID', models.IntegerField(max_length=100)),
                ('service', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='dueamt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amtdue', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('usage', models.FloatField(max_length=100)),
                ('validity', models.IntegerField(max_length=100)),
                ('amount', models.IntegerField(max_length=100)),
            ],
        ),
    ]
