# Generated by Django 4.0.5 on 2022-07-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoizApp', '0002_dongle_postpaid_prepaid_recharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('number', models.BigIntegerField(max_length=11)),
                ('address', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(help_text='mm/dd/yy Hour:Min')),
                ('type', models.CharField(help_text='small case please', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(max_length=20)),
                ('Describe_your_issue', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='recharging',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.BigIntegerField(max_length=11)),
                ('type', models.CharField(help_text='small case please', max_length=100)),
                ('amt', models.IntegerField()),
            ],
        ),
    ]
